-- contacts table
create table contacts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    owner_id uuid not null references profiles,
    name varchar,
    phone varchar not null,
    country_code varchar
);