--custom messages
create table custom_messages (
    id bigint generated by default as identity primary key unique,
    owner_id uuid,
    custom_sms_message text default 'Hey [[" contact_name "]]! [[" user_name "]] didn''''t achieve their goal: [[" goal_title "]]'::text not null,
    custom_voice_message text default 'Hey [[" contact_name "]]! [[" user_name "]] didn''''t achieve their goal: [[" goal_title "]]'::text not null,
    created_at timestamp with time zone default now()
);