create table tattles(
    id bigint generated by default as identity primary key unique,
    goal_id bigint not null references goals,
    contact_id bigint not null references contacts,
    message_type varchar default 'sms'::character varying not null,
    message_body text,
    created_at timestamp with time zone default now(),
    owner_id uuid not null references profiles
);