-- stripe_subscriptions table
create table stripe_subscriptions (
    id bigserial constraint stripe_subscriptions_pk primary key,
    created_at           date default now(),
    data_type            varchar,
    account_country      varchar,
    account_name         varchar,
    amount_due           bigint,
    amount               bigint,
    amount_capturable    bigint,
    amount_received      bigint,
    amount_paid          bigint,
    amount_remaining     bigint,
    attempt_count        bigint,
    attempted            boolean,
    auto_advance         boolean,
    balance_transaction  varchar,
    billing_reason       varchar,
    billing_cycle_anchor bigint,
    collection_method    varchar,
    created              bigint,
    currency             varchar,
    customer_id          varchar,
    customer_email       varchar,
    charge               varchar,
    captured             boolean,
    cancel_at            bigint,
    cancel_at_period_end boolean,
    canceled_at          bigint,
    capture_method       varchar,
    card_brand           varchar,
    card_country         varchar,
    card_exp_month       varchar,
    card_exp_year        varchar,
    card_fingerprint     varchar,
    card_funding         varchar,
    card_last_four       varchar,
    card_network         varchar,
    card_three_d_secure  varchar,
    card_wallete         varchar,
    client_secret        varchar,
    confirmation_method  varchar,
    current_period_end   bigint,
    current_period_start bigint,
    description          varchar,
    dispute              varchar,
    disputed             boolean,
    ending_balance       bigint,
    hosted_invoice_url   varchar,
    invoice_pdf          varchar,
    invoice_id           varchar,
    livemode             boolean,
    latest_invoice_id    varchar,
    number               varchar,
    network_status       varchar,
    outcome_type         varchar,
    payment_intent       varchar,
    paid                 boolean,
    payment_intent_id    varchar,
    payment_method_id    varchar,
    plan_price_id        varchar,
    plan_active          boolean,
    plan_amount          bigint,
    plan_created         bigint,
    plan_interval        varchar,
    plan_interval_count  bigint,
    plan_product_id      varchar,
    receipt_number       varchar,
    receipt_url          varchar,
    risk_level           varchar,
    risk_score           bigint,
    seller_message       varchar,
    setup_future_usage   varchar,
    statement_descriptor varchar,
    status               varchar,
    start_date           bigint,
    subscription_id      varchar,
    subtotal             bigint,
    trial_end            bigint,
    trial_start          bigint,
    tax                  varchar,
    total                bigint,
    amount_captured      bigint

    create unique index stripe_subscriptions_id_uindex
    on stripe_subscriptions (id);
);